Platform integration preparation
Cryptorubic/rubic-sdk pull request #105
Opened 2022-06-23 13:19 UTC by axtezy

2022-06-23 15:06 UTC, ottebrut requested changes

2022-06-23 15:06 UTC, ottebrut commented on src/features/instant-trades/models/trade-type.ts
> +export const ONEINCH_TRADE_TYPE = {
я по блокчейнам объединял, можно обсудить

2022-06-23 15:06 UTC, ottebrut commented on webpack.config.js
> +            module: {
съехали табы

2022-06-24 13:24 UTC, axtezy commented on src/features/instant-trades/dexes/common/oneinch-common/oneinch-abstract-provider.ts
> -        const supportedTokensAddresses = await this.getSupportedTokensByBlockchain();
Потому что токены поддерживаются на самом деле, на инче и у нас на платформе можно свапнуть

2022-06-24 13:25 UTC, axtezy commented on package.json
> +    "typescript": "^4.6.3",
Конфликтовало с ангуляром, когда в платформу интегрировал

2022-06-24 13:26 UTC, axtezy commented on package.json
> +    "typescript": "^4.6.3",
Конфликтовало с ангуляром, когда в платформу интегрировал

2022-06-24 13:26 UTC, axtezy commented on src/features/instant-trades/dexes/common/oneinch-common/oneinch-abstract-provider.ts
> -        const supportedTokensAddresses = await this.getSupportedTokensByBlockchain();
Потому что токены поддерживаются на самом деле, на инче и у нас на платформе можно свапнуть

2022-06-29 11:12 UTC, ottebrut requested changes

2022-06-29 11:12 UTC, ottebrut commented on src/features/instant-trades/instant-trades-manager.ts
> +            return 0;
Зачем проверка на instanceOf если ты уже отфильтровал по notNull?

2022-07-05 05:49 UTC, axtezy commented on src/features/instant-trades/instant-trades-manager.ts
> +            return 0;
Удалил `notNull`, мне тут только сортировка нужна была

2022-07-05 08:04 UTC, ottebrut approved these changes

2022-07-05 09:27 UTC, merged