Add reactive trade calculation
Cryptorubic/rubic-sdk pull request #120
Opened 2022-07-11 09:28 UTC by axtezy

2022-07-11 09:56 UTC, axtezy commented on package.json
> +  "homepage": "https://githusb.com/Cryptorubic/rubic-sdk",
Убрать

2022-07-11 13:54 UTC, ottebrut requested changes

2022-07-11 13:54 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +                        // eslint-disable-next-line @typescript-eslint/no-unused-vars
если еще не добавили, то нужно добавить в eslint правило, чтобы переменные с _ игнорировались

2022-07-11 13:54 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +     * @param oldTrade New trade to compare
перепутал описание

2022-07-12 07:44 UTC, axtezy commented on src/features/cross-chain/cross-chain-manager.ts
> +                        // eslint-disable-next-line @typescript-eslint/no-unused-vars
Тут деструктуризация, это отдельная настройка этого правила. Но у меня почему то не работает, мб в новой версии eslint только, пока решил так оставить, потом обновим

2022-07-12 08:08 UTC, ottebrut approved these changes

2022-07-12 08:13 UTC, merged