Feature/via exchange
Cryptorubic/rubic-sdk pull request #146
Opened 2022-08-08 14:51 UTC by ottebrut

2022-08-25 07:00 UTC, axtezy requested changes

2022-08-25 07:22 UTC, kolebayevv requested changes

2022-08-25 07:22 UTC, kolebayevv commented on src/features/cross-chain/providers/via-trade-provider/via-cross-chain-trade-provider.ts
> +            const via = new Via({
мб один раз создать экземпляр как поле класса ?

2022-08-25 07:22 UTC, kolebayevv commented on src/features/cross-chain/utils/decode-method.ts
> +        return retData;
не оч понятное название переменной

2022-08-25 07:22 UTC, kolebayevv commented on src/features/cross-chain/providers/via-trade-provider/via-cross-chain-trade-provider.ts
> +            const gasData = options.gasCalculation === 'enabled' ? null : null;
`null` или `null`?

2022-08-25 07:22 UTC, kolebayevv commented on src/features/cross-chain/providers/lifi-trade-provider/lifi-cross-chain-trade-provider.ts
> +            ?.tool.toLowerCase();
по идее перед `toLowerCase()` тоже нужен `?`

2022-08-25 07:22 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-manager.ts
> +     * @param oldWrappedTrade Old trade to compare.
я бы назвал `prevWrapperTrade` и `nextWrappedTrade`

2022-08-25 11:34 UTC, ottebrut commented on src/features/cross-chain/providers/via-trade-provider/via-cross-chain-trade-provider.ts
> +            const via = new Via({
В конструктор Via передается таймаут, который может передается в options у функции calculate. Поэтому я создаю объект в функции calculate.

2022-08-25 11:37 UTC, ottebrut commented on src/features/cross-chain/providers/lifi-trade-provider/lifi-cross-chain-trade-provider.ts
> +            ?.tool.toLowerCase();
tool не может быть undefined (согласно lifi sdk)

2022-08-25 11:38 UTC, ottebrut commented on src/features/cross-chain/providers/via-trade-provider/via-cross-chain-trade-provider.ts
> +        return Injector.httpClient
поменял

2022-08-25 11:38 UTC, ottebrut commented on src/features/cross-chain/utils/decode-method.ts
> +        return retData;
поменял

2022-08-25 11:38 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +     * @param oldWrappedTrade Old trade to compare.
поменял

2022-08-25 12:01 UTC, ottebrut commented on src/features/cross-chain/providers/via-trade-provider/via-cross-chain-trade-provider.ts
> +            const gasData = options.gasCalculation === 'enabled' ? null : null;
добавил рассчет

2022-08-26 10:55 UTC, kolebayevv approved these changes

2022-08-26 12:21 UTC, merged