Cross chain
Cryptorubic/rubic-sdk pull request #16
Opened 2021-12-27 11:38 UTC by ottebrut

2021-12-28 17:15 UTC, siandreev requested changes

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract getFirstPath(): string[];
public, но мутабельнй и string, а не Token?

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +        }, '');
может это в utils вынести?

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/cross-chain-manager.ts
> +                price: new BigNumber(NaN)
тут принципиально не нужна цена? Вроде этот объект потом наружу передается из публичного метода. Может лучше `PriceToken.createFromToken()`?

2021-12-28 17:15 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +    public readonly wrappedPath: ReadonlyArray<Token>;
зачем public?

2021-12-28 17:15 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +    wrappedPath: ReadonlyArray<Token> | Token[];
надо еще в 1inch-е переименовать

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/contract-data/contract-data.ts
> +    public async getNumOfBlockchain(): Promise<number> {
не супер критично, но мне почему-то режет глаз этот `Num`, имхо лучше написать полностью, имя и так длинное

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/constants/cross-chain-contracts.ts
> +                methodSuffix: '1'
а о чем вы в итоге договорились? Что это, и почему именно 1?

2021-12-28 17:15 UTC, siandreev commented on src/features/cross-chain/contract-data/models/provider-data.ts
> +    provider: UniswapV2AbstractProvider;
также касается остальных мест, где используется этот интерфейс: почему именно UniswapV2AbstractProvider? Мы же будем переходить на 1inch и uniV3. Может сразу более общий тип сделать -- InstantTradeProvider? Или создать интерфейс типа CrosschainInstantTradeProvider, который будет объединением поддерживаемых провайдеров?

2021-12-29 09:15 UTC, ottebrut commented on src/features/cross-chain/contract-data/contract-data.ts
> +export class ContractData {
Data - потому что с помощью этого класса берется информация о данных контракта и данных метода для свопа. 
Кросс чейн я убрал, потому что он и так в папке кросс-чейн и можно сократить название.

2021-12-29 09:20 UTC, ottebrut commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract get path(): ReadonlyArray<Token>;
Не очень понимаю зачем убирать геттеры? В них просто берется информация из полей, которые ридонли. Мы решали, что это нормально.

2021-12-29 09:22 UTC, ottebrut commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +        }, '');
Это довольно специфичная обработка, которая только для этого случая подходит. Можно будет вынести, если кому то еще подобное понадобится.

2021-12-29 09:26 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +                price: new BigNumber(NaN)
Для пользователя они не будут публичными. И это будут лишние запросы.

2021-12-29 09:26 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +    public readonly wrappedPath: ReadonlyArray<Token>;
Потому что нужно для кросс чейна. Не знаю, как лучше это сделать.

2021-12-29 09:27 UTC, ottebrut commented on src/features/cross-chain/contract-data/contract-data.ts
> +    public async getNumOfBlockchain(): Promise<number> {
Так называется поле в самом контракте. Мне лучше все одинаково с методами контракта называть, чтобы не путаться.

2021-12-29 09:28 UTC, ottebrut commented on src/features/cross-chain/constants/cross-chain-contracts.ts
> +                methodSuffix: '1'
Если есть два провайдера типа uni-swap-v2, то каждому следующему провайдера к названию функции прибавляется индекс (swapTokensToOtheBlockchain1)

2021-12-29 09:30 UTC, ottebrut commented on src/features/cross-chain/contract-data/models/provider-data.ts
> +    provider: UniswapV2AbstractProvider;
Ну пока полностью протестчены только в2, поэтому я не стал усложнять и добавил только для них обработку. Позже добавлю для других.

2021-12-29 09:30 UTC, ottebrut commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +                false,
добавил комменты

2021-12-29 09:31 UTC, ottebrut commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract getFirstPath(): string[];
поменял на protected

2021-12-29 09:32 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +    wrappedPath: ReadonlyArray<Token> | Token[];
для 1inch другая ситуация, там норм название

2021-12-29 10:27 UTC, siandreev commented on src/features/cross-chain/contract-data/contract-data.ts
> +export class ContractData {
> CrossChain я убрал, потому что он и так в папке кросс-чейн (и использоваться должен только там) и можно сократить название.

Просто потом у нас может быть более общий класс с таким же названием. Мне кажется, лучше чтобы названия классов были самодостаточны без информации о файловой структуре -- файл может быть перемещен + в коде мы редко смотрим на имопорты (в отличие от названий сущностей)

2021-12-29 10:33 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract get path(): ReadonlyArray<Token>;
Если у нас все ридонли и не мутабельное, то такие геттеры нам не нужны. Имхо для единообразия лучше делать все тогда уж ридонли полями, иначе может возникнуть иллюзия, что раз тут использован геттер, то в этом есть какой-то особенный смысл

2021-12-29 10:33 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +                false, // TODO add processing of tokens with fee (now `false` for common tokens)
давай лучше в константы все-таки вынесем. Мне кажется, константа  `useExactInputMethod` будет смотреться лучше, чем захардкоженый false с комментом

2021-12-29 10:33 UTC, siandreev commented on src/features/cross-chain/constants/cross-chain-contracts.ts
> +                methodSuffix: '1'
Давай напишем об этом коммент

2021-12-29 10:33 UTC, siandreev commented on src/features/cross-chain/contract-data/contract-data.ts
> +    public async getNumOfBlockchain(): Promise<number> {
ок

2021-12-29 10:34 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +    public readonly wrappedPath: ReadonlyArray<Token>;
ок

2021-12-29 10:35 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +        }, '');
тогда хотя бы в отдельный метод. Имхо это супер низкоуровневый код

2021-12-29 10:35 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract getFirstPath(): string[];
ок

2021-12-29 10:37 UTC, siandreev commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +    public abstract get path(): ReadonlyArray<Token>;
Если у нас все ридонли и не мутабельное, то такие геттеры нам не нужны. Имхо для единообразия лучше делать все тогда уж ридонли полями, иначе может возникнуть иллюзия, что раз тут использован геттер, то в этом есть какой-то особенный смысл

2021-12-29 10:42 UTC, siandreev commented on src/features/cross-chain/cross-chain-manager.ts
> +                price: new BigNumber(NaN)
Предлагаю тогда в instant trade provider-e сделать to как PriceToken | Token. Иначе в этом месте явно нарушается interface segregation, потому что для расчета price не нужен, но мы насильно пихаем заглушку

2021-12-29 10:45 UTC, siandreev commented
кст у тебя `yarn compile` работает в ветке? У меня падает

2021-12-29 14:05 UTC, siandreev approved these changes

2021-12-29 14:05 UTC, merged