RUBIC-633: rango integration
Cryptorubic/rubic-sdk pull request #164
Opened 2022-08-18 14:02 UTC by kolebayevv

2022-08-22 08:55 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +            methodArguments.push(fromContracts.providerGateway);
на 136 и 142 строках вместо полей обьекта fromContracts будет адрес из  ответа апишки ранго, т.к. их собственные контракты используются только для cbridge, multichain, в остальных случаях - будет адрес агрегированного ими провайдера

2022-08-22 13:10 UTC, axtezy requested changes

2022-08-22 13:10 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        trade: null,
Если route есть, то лучше все-равно отдавать трейд, прикрепляя CrossChainMinMaxAmountError

2022-08-22 13:10 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        priceImpact: 0,
priceImpact из апи не возвращается?

2022-08-22 13:10 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        ...((tx as EvmTransaction)?.gasLimit
Зачем газ дата? Мы сами же считаем газ, можно без подсчета ранго обойтись

2022-08-22 13:10 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +    private async checkContractState(fromBlockchain: RangoCrossChainSupportedBlockchain) {
Давай вынесем в CrossChainTradeProvider весь метод как protected, но чтобы он принимал адрес роутера

2022-08-22 13:10 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +            methodArguments.push(fromContracts.providerGateway);
Нам у адреса всех провайдеров через которые свапы идут надо на контракт заносить. У ранго есть полный список?

2022-08-22 13:38 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +            methodArguments.push(fromContracts.providerGateway);
надо узнать

2022-08-22 13:39 UTC, kolebayevv commented on package.json
> +  "version": "2.10.14",
да это для тестов пока

2022-08-22 15:11 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        priceImpact: 0,
no

2022-08-23 06:49 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        trade: null,
Но может быть что придет? Или если amount restriction, то трейда всегда нет?

2022-08-23 06:50 UTC, axtezy commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        priceImpact: 0,
Надо тогда наверн сделать тип `number | null` для `priceImpact`, а то 0 не совсем корректно получается

2022-08-23 07:39 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        trade: null,
да, path и tx будет null

2022-08-23 09:38 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +    private async checkContractState(fromBlockchain: RangoCrossChainSupportedBlockchain) {
done

2022-08-23 09:38 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +                        ...((tx as EvmTransaction)?.gasLimit
done

2022-08-23 09:38 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-status-manager.ts
> +        const apiUrl = '';
done

2022-08-23 09:38 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-manager.ts
> +            disabledProviders: ['RUBIC', 'CELER', 'LIFI', 'SYMBIOSIS', 'DEBRIDGE'],
done

2022-08-23 15:08 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/models/rango-providers.ts
> +    OSMOSIS: 'Osmosis',
удалил ненужных провайдеров

2022-08-24 14:25 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +        const subType = path?.find(
done

2022-08-24 15:22 UTC, axtezy approved these changes

2022-08-30 10:44 UTC, ottebrut requested changes

2022-08-30 10:44 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +            toAddress: options?.toAddress || Injector.web3Private.address
достаточно просто Injector.web3Private.address

2022-08-30 10:44 UTC, ottebrut commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +        // }
надо что то с этим решить

2022-08-30 10:44 UTC, ottebrut commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +    public cryptoFeeToken: PriceTokenAmount;
readonly

2022-08-30 10:44 UTC, ottebrut commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +    public readonly gasData: GasData | null = null;
почему не считать?

2022-08-30 10:45 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +        // }
я пока не вижу смысла в этом запросе, тут только для проверки токенов можно его использовать, если токен не поддерживается мы не отдаем трейд, и при этом если сделать запрос на свап с неподдерживаемой парой они вернут стандартную ошибку NO_ROUTE и мы также не отдаем трейд

2022-08-30 10:47 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-manager.ts
> +            toAddress: options?.toAddress || Injector.web3Private.address
done

2022-08-30 10:48 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +    public cryptoFeeToken: PriceTokenAmount;
done

2022-08-30 11:14 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +    public readonly gasData: GasData | null = null;
я ее считаю в swap методе, между вызовом мм и получением данных для транзы

2022-08-30 16:45 UTC, ottebrut commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +        // }
может тогда просто удалить эту часть?

2022-08-31 07:58 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade-provider.ts
> +        // }
done

2022-08-31 14:14 UTC, kolebayevv commented on src/features/cross-chain/providers/rango-trade-provider/rango-cross-chain-trade.ts
> +    public readonly gasData: GasData | null = null;
сделал как у остальных провайдеров

2022-09-02 09:29 UTC, merged