Rubic 588/transaction cancellation
Cryptorubic/rubic-sdk pull request #168
Opened 2022-08-22 14:09 UTC by Doctor-Cyclone

2022-08-23 08:55 UTC, axtezy requested changes

2022-08-23 08:55 UTC, axtezy commented on src/core/blockchain/web3-public/models/pending-transaction.ts
> +export interface PendingTransaction {
Расписать интерфейс с JSDoc

2022-08-23 17:51 UTC, ottebrut commented
Поменяй целевую ветку на develop

2022-08-25 07:59 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-status-manager.ts
> +            console.log('Tx Indexing Time Spent', txIndexingTimeSpent);
если pr готов к вливанию - консоль логи надо убрать

2022-08-29 08:03 UTC, ottebrut requested changes

2022-08-29 08:03 UTC, ottebrut commented on src/features/cross-chain/cross-chain-status-manager.ts
>          if (srcTxReceipt === null) {
это можно вынести в самый верх функции, так как эта часть независима

2022-08-29 08:04 UTC, ottebrut requested changes

2022-08-29 08:04 UTC, ottebrut commented on src/features/cross-chain/cross-chain-status-manager.ts
>          }
это можно вынести в самый верх функции, так как эта часть независима

2023-02-15 08:23 UTC, closed without merging