Update rpc provider logic for web3 public
Cryptorubic/rubic-sdk pull request #173
Opened 2022-08-29 07:49 UTC by ottebrut

2022-08-30 05:10 UTC, axtezy requested changes

2022-09-05 09:30 UTC, ottebrut commented on src/core/blockchain/web3-public/web3-public-service.ts
> +        this.rpcListProvider = Object.keys(rpcList).reduce((acc, blockchainName) => {
добавил

2022-09-05 09:30 UTC, ottebrut commented on src/core/blockchain/web3-public/web3-public-service.ts
> +                if (!rpcConfig.rpcList?.length) {
добавил

2022-09-05 09:31 UTC, ottebrut commented on src/core/sdk/models/configuration.ts
> +    readonly mainRpc?: string;
избавимся от полей mainRpc и spareRpc, когда будем избавляться от легаси
пометил их deprecated

2022-09-05 10:11 UTC, axtezy approved these changes

2022-09-05 10:36 UTC, kolebayevv approved these changes

2022-09-05 11:58 UTC, ottebrut commented on src/core/blockchain/web3-public/web3-public.ts
> +            throwRpcError?: boolean;
убрали эту логику и просто увеличили время для расчета ИТ

2022-09-06 13:36 UTC, merged