RUBIC-697: get 1inch allowance from blockchain
Cryptorubic/rubic-sdk pull request #184
Opened 2022-09-07 09:42 UTC by kolebayevv

2022-09-08 10:18 UTC, kolebayevv commented
**QA APPROVED**

2022-09-12 10:26 UTC, axtezy approved these changes

2022-09-12 10:27 UTC, axtezy requested changes
2.15.1 Версия уже есть

2022-09-12 13:32 UTC, axtezy approved these changes

2022-09-12 14:37 UTC, merged