RUBIC-713: return destination tx hash with cross-chain status
Cryptorubic/rubic-sdk pull request #196
Opened 2022-09-14 12:15 UTC by kolebayevv

2022-09-14 12:24 UTC, axtezy requested changes

2022-09-14 12:24 UTC, axtezy commented on src/features/cross-chain/cross-chain-status-manager.ts
> +        const dstTxData = await this.getDstTxStatus(
Надо тогда функции переименовать в `getDstTxData`

2022-09-14 12:43 UTC, axtezy requested changes
Версию поднять

2022-09-16 09:51 UTC, kolebayevv commented on src/features/cross-chain/cross-chain-status-manager.ts
> +        const dstTxData = await this.getDstTxStatus(
done

2022-09-16 11:41 UTC, axtezy approved these changes

2022-09-20 13:16 UTC, merged