Feature/bridgers integration
Cryptorubic/rubic-sdk pull request #216
Opened 2022-09-26 11:01 UTC by ottebrut

2022-09-26 12:06 UTC, axtezy requested changes

2022-09-26 12:06 UTC, axtezy commented on src/features/on-chain/providers/abstract/on-chain-trade/on-chain-trade.ts
> +    public abstract slippageTolerance: number;
А зачем нам не readonly слипейдж? Может запретим менять?

2022-09-26 19:40 UTC, ottebrut commented on src/core/blockchain/web3-private-service/web3-private/tron-web3-private/tron-web3-private.ts
> +        let rawValue: BigNumber;
исправил

2022-09-26 19:40 UTC, ottebrut commented on src/core/blockchain/web3-private-service/web3-private/web3-private.ts
> +    public async checkBlockchainCorrect(blockchainName: BlockchainName): Promise<void | never> {
добавил

2022-09-26 19:40 UTC, ottebrut commented on src/core/blockchain/web3-pure/typed-web3-pure/evm-web3-pure.ts
> +        return Boolean(address) && address === EvmWeb3Pure.EMPTY_ADDRESS;
исправил

2022-09-26 19:41 UTC, ottebrut commented on src/features/cross-chain/cross-chain-status-manager/cross-chain-status-manager.ts
> +            if (BlockchainsInfo.isEvmBlockchainName(fromBlockchain)) {
добавил

2022-09-26 19:41 UTC, ottebrut commented on src/features/on-chain/providers/abstract/on-chain-trade/on-chain-trade.ts
> +    public abstract slippageTolerance: number;
исправил

2022-09-27 09:17 UTC, axtezy approved these changes

2022-09-27 13:31 UTC, merged