Rubic 805/tokens with commissions
Cryptorubic/rubic-sdk pull request #232
Opened 2022-10-25 11:24 UTC by kolebayevv

2022-10-27 07:55 UTC, axtezy requested changes

2022-10-27 07:55 UTC, axtezy commented on src/core/blockchain/web3-public-service/web3-public/evm-web3-public/evm-web3-public.ts
> +    public async staticCallContractMethod(
Описание на публичный метод

2022-10-27 07:55 UTC, axtezy commented on src/features/deflation-token-manager/deflation-token-manager.ts
> +export class DeflationTokenManager {
Зачем отдельно manager? Почему в класс токен просто не вынести?

2022-10-27 08:01 UTC, kolebayevv commented on src/features/deflation-token-manager/deflation-token-manager.ts
> +export class DeflationTokenManager {
там просто нужно инстант трейды строить для проверки и тогда у токена появится OnChainManager в зависимостях, выглядит не оч на мой взгляд

2022-10-31 08:04 UTC, kolebayevv commented on src/core/blockchain/web3-public-service/web3-public/evm-web3-public/evm-web3-public.ts
> +    public async staticCallContractMethod(
done

2022-10-31 15:02 UTC, axtezy approved these changes

2022-10-31 15:53 UTC, merged