Rubic-825: add aggregator providers filter
Cryptorubic/rubic-sdk pull request #233
Opened 2022-10-28 12:06 UTC by kolebayevv

2022-10-28 14:38 UTC, axtezy requested changes

2022-10-28 14:38 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/lifi-provider/lifi-cross-chain-provider.ts
> +            Object.values(LifiBridgeTypes).includes(bridgeType)
`Object.values(LifiBridgeTypes)` вынести из цикла в константу

2022-10-28 14:50 UTC, kolebayevv commented on src/features/cross-chain/calculation-manager/providers/lifi-provider/lifi-cross-chain-provider.ts
> +            Object.values(LifiBridgeTypes).includes(bridgeType)
done

2022-11-03 08:41 UTC, axtezy approved these changes

2022-11-03 12:26 UTC, merged