Feature/cross chain reactive routes fixes
Cryptorubic/rubic-sdk pull request #244
Opened 2022-11-08 09:16 UTC by ottebrut

2022-11-09 08:09 UTC, axtezy requested changes

2022-11-09 08:09 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/bridgers-provider/evm-bridgers-trade/evm-bridgers-cross-chain-trade.ts
> +        isNative: true
Для интеграторов будет непонятно что такое native в контексте бриджа, можно подумать что это нативный мост сети от разрабов блокчейна
Мне кажется, лучше сделать `isAggregator` поле

2022-11-09 20:59 UTC, ottebrut commented on src/features/cross-chain/calculation-manager/cross-chain-manager.ts
> +                        calculatedTrades += 1;
обновил

2022-11-09 21:00 UTC, ottebrut commented on src/features/cross-chain/calculation-manager/providers/bridgers-provider/evm-bridgers-trade/evm-bridgers-cross-chain-trade.ts
> +        isNative: true
создал в трейде отдельно поле `isAggregator`

2022-11-10 09:13 UTC, axtezy approved these changes

2022-11-10 09:19 UTC, merged