Feature/uni v3
Cryptorubic/rubic-sdk pull request #28
Opened 2022-01-13 15:14 UTC by ottebrut

2022-01-14 08:59 UTC, siandreev requested changes

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +    private async getRouterTokens(): Promise<Token[]> {
getOrCreateRouterTokens

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +                !compareAddresses(token.address, toToken.address)
мне кажется, `!token.isEqualTo(from) && !token.isEqualTo(toToken)` будет понятнее и красивее

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/constants/quoter-contract-data.ts
> +        name: 'quoteExactOutput',
лишнее

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/constants/quoter-contract-data.ts
> +        name: 'quoteExactOutputSingle',
лишнее

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +    private readonly web3Public = Injector.web3PublicService.getWeb3Public(BLOCKCHAIN_NAME.POLYGON);
должен быть ленивым (инстанс квотера создается в конструкторе провайдера, если поменяется конфигурация все сломается), можно сделать геттер

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +        this.web3Public = Injector.web3PublicService.getWeb3Public(blockchain);
см. коммент про ленивость из квотера алгебры

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/algebra-trade.ts
> +                        0
давай лучше в переменную

2022-01-14 08:59 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-trade.ts
> +    }
как и в провайдере, предлагаю использоватьл шаблонный метод, и абстрагировать этот класс от конкретных реализаций

2022-01-14 11:10 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
> +
поправил

2022-01-14 11:10 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
> +        });
поправил

2022-01-14 11:10 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
> +            !this.isUniswapV3 &&
это только рубик оптимизация, переименовал, чтобы понятнее было

2022-01-14 11:12 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/models/uniswap-v3-algebra-quoter-controller.ts
> +    ): Promise<(UniswapV3Route | AlgebraRoute)[]>;
поправил

2022-01-14 11:12 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +    private async getRouterTokens(): Promise<Token[]> {
поправил

2022-01-14 11:12 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +                !compareAddresses(token.address, toToken.address)
поправил

2022-01-14 11:13 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/constants/quoter-contract-data.ts
> +        name: 'quoteExactOutput',
Это понадобится позже. Оказывается, метода exactOutput все таки нужен для вычислений

2022-01-14 11:13 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/constants/quoter-contract-data.ts
> +        name: 'quoteExactOutputSingle',
выше написал

2022-01-14 11:13 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +    private readonly web3Public = Injector.web3PublicService.getWeb3Public(BLOCKCHAIN_NAME.POLYGON);
поправил

2022-01-14 11:13 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +        this.web3Public = Injector.web3PublicService.getWeb3Public(blockchain);
поправил

2022-01-14 11:14 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/algebra-trade.ts
> +                        0
я не понимаю работу это параметра и мне кажется тут достаточно комментария

2022-01-14 11:14 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-trade.ts
> +    }
поправил

2022-01-14 13:56 UTC, siandreev requested changes

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +                        0 // sqrtPriceLimitX96
уже в прошлый раз об этом спорили, но давай все-таки такие штуки решать за счет переменных, а не комментов. Пусть лучше будет переменная `sqrtPriceLimitX96 ` с комментом-референсом на код контракта. Все-таки так советует делать дядюшка Боб, и я с ним согласен, выглядит чище

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-abstract/uniswap-v3-abstract-provider.ts
> +        return false;
почему false?

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +                        !routerToken.isEqualTo(firstToken) && !routerToken.isEqualTo(secondToken)
Сорри за повторный коммент в этом месте, только сейчас подумал: у нас такой код очень много где встречается. Может, сделать метод `token.isEqualToSome(tokens Token[]): boolean`?

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
>      }
можно сделать полем

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-trade.ts
> +    protected abstract unwrapWethMethodName: 'unwrapWETH9' | 'unwrapWNativeToken';
мне кажется, лучше `string` -- базовый класс не должен знать о деталях реализации в наследниках. Если добавится новый наследник, то не нужно будет менять тип

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
> +    ): Promise<T | AlgebraTrade> {
тоже нарушает инкапсуляцию, может лучше какой-нибудь общий тип трейдов юни в3 и алгебры? Или дженерик

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +                        0 // limitSqrtPrice
писал выше, давай тоже в переменную лучше с референсом на контракт

2022-01-14 13:56 UTC, siandreev commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +            token => !token.isEqualTo(from) && !token.isEqualTo(toToken)
писал выше про `isEqualToSome`

2022-01-17 11:23 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-abstract/uniswap-v3-abstract-provider.ts
> +        return false;
Сейчас для юни в3 рубик оптимизация работает 7 секунд, поэтому она отключена.

2022-01-17 11:29 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-trade.ts
> +    protected abstract unwrapWethMethodName: 'unwrapWETH9' | 'unwrapWNativeToken';
В данном случае базовый класс содержит всю реализацию и использует этот метод, единственная разница в его названии. Поэтому, мне кажется, лучше, чтобы базовый класс явно ограничивал, каким может быть это поле.
+ Этот класс сделан специально для юни в3 и алгебры, поэтому, если добавится новый наследник, то это предполагает какие то важные изменения в классе и явное изменения этого поля.

2022-01-17 11:36 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
> +    ): Promise<T | AlgebraTrade> {
Я пытался сделать дженериком по разному, но по типам не сходится:
1) Нельзя писать typeof T
2) Если по примеру с uni v2: 
 a) в uni-v3-algebra-provider создать тип UniV3AlgebraClass<T>
 b) в uni-v3 создать тип UniV3Class<T>
 То компилятор не поймет, что UniV3Class<T> сводится к UniV3AlgebraClass<T> (и логично, что компилятор не поймет)

Поэтому я написал единственным рабочим способом, который придумал.

2022-01-17 11:42 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +                        0 // sqrtPriceLimitX96
поправил

2022-01-17 11:42 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-abstract/utils/quoter-controller/uniswap-v3-quoter-controller.ts
> +                        !routerToken.isEqualTo(firstToken) && !routerToken.isEqualTo(secondToken)
добавил

2022-01-17 11:42 UTC, ottebrut commented on src/features/swap/dexes/common/uniswap-v3-algebra-abstract/uniswap-v3-algebra-abstract-provider.ts
>      }
поправил

2022-01-17 11:42 UTC, ottebrut commented on src/features/swap/dexes/polygon/algebra/utils/quoter-controller/algebra-quoter-controller.ts
> +                        0 // limitSqrtPrice
поправил

2022-02-15 14:13 UTC, merged