Feature/change now
Cryptorubic/rubic-sdk pull request #328
Opened 2023-02-17 09:34 UTC by Doctor-Cyclone

2023-02-20 10:44 UTC, axtezy requested changes

2023-02-20 10:44 UTC, axtezy commented on src/common/tokens/constants/wrapped-native-tokens.ts
> +export const wrappedNativeTokensList: Partial<Record<EvmBlockchainName, Token>> = {
Зачем?

2023-02-20 10:44 UTC, axtezy commented on src/common/tokens/token.ts
> +        return this.address === EMPTY_ADDRESS;
зачем сравнение с EMPTY_ADDRESS?

2023-02-20 10:44 UTC, axtezy commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    ...Object.values(BLOCKCHAIN_NAME).reduce(
В отдельную константу

2023-02-20 10:44 UTC, axtezy commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    [BLOCKCHAIN_NAME.BITCOIN_CASH]: 10000,
Это не эвм блокчейна и те что выше тоже в основном

2023-02-20 10:44 UTC, axtezy commented on src/core/blockchain/web3-public-service/web3-public/constants/multicall-addresses.ts
> +    ...Object.values(web3PublicSupportedBlockchains).reduce(
вынести в константу отдельную

2023-02-20 10:44 UTC, axtezy commented on src/core/blockchain/web3-pure/constants/empty-address.ts
> +export const EMPTY_ADDRESS = '0x0000000000000000000000000000000000000000';
У нас же есть уже 0x00 константа

2023-02-20 10:44 UTC, axtezy commented on src/features/common/utils/check-address.ts
> +        return true;
почему тру? Если мы не можем проверить наверное false надо выставлять

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/celer-provider/celer-cross-chain-contract-data.ts
> +        const nativeToken = nativeTokensList[this.blockchain] as Token<EvmBlockchainName>;
зачем явное преобразование?

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/changenow-provider/changenow-cross-chain-provider.ts
> +    readonly type = CROSS_CHAIN_TRADE_TYPE.CHANGENOW;
модфификатор доступа

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/changenow-provider/changenow-cross-chain-provider.ts
> +            {
в 1 строчку объект не помещается?)

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/symbiosis-provider/constants/contract-address-v2.ts
> -    [BLOCKCHAIN_NAME.BITCOIN]: {
За что так с биткойном?

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/symbiosis-provider/constants/symbiosis-cross-chain-supported-blockchain.ts
> +    // BLOCKCHAIN_NAME.BITCOIN
Почему убрал?

2023-02-20 10:44 UTC, axtezy commented on src/features/cross-chain/status-manager/cross-chain-status-manager.ts
> +                    params: {
тут тоже можно в несколько строчек

2023-02-20 10:44 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/dexes/aurora/default-constants.ts
> +    wrappedNativeTokensList[BLOCKCHAIN_NAME.AURORA]!.address, // WETH
нужно переделать тип, чтобы такой костыль не нужен был

2023-02-20 11:24 UTC, Doctor-Cyclone commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    [BLOCKCHAIN_NAME.BITCOIN_CASH]: 10000,
Судя по доку, это всё EVM сети.

2023-02-20 11:44 UTC, axtezy commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    [BLOCKCHAIN_NAME.BITCOIN_CASH]: 10000,
bitcoin cash это точно не евм

2023-02-21 09:07 UTC, Doctor-Cyclone commented on src/common/tokens/constants/wrapped-native-tokens.ts
> +export const wrappedNativeTokensList: Partial<Record<EvmBlockchainName, Token>> = {
Done.

2023-02-21 09:07 UTC, Doctor-Cyclone commented on src/common/tokens/token.ts
> +        return this.address === EMPTY_ADDRESS;
Done.

2023-02-21 09:07 UTC, Doctor-Cyclone commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    ...Object.values(BLOCKCHAIN_NAME).reduce(
Done.

2023-02-21 09:08 UTC, Doctor-Cyclone commented on src/core/blockchain/utils/blockchains-info/constants/blockchain-id.ts
> +    [BLOCKCHAIN_NAME.BITCOIN_CASH]: 10000,
https://docs.google.com/spreadsheets/d/15C226VpSLgROxf-vKKIZNljAhZ61ciQApdUGGYS6-nU/edit#gid=1883547013

вот док, отталкивался на него

2023-02-21 09:08 UTC, Doctor-Cyclone commented on src/core/blockchain/web3-public-service/web3-public/constants/multicall-addresses.ts
> +    ...Object.values(web3PublicSupportedBlockchains).reduce(
Done.

2023-02-21 09:08 UTC, Doctor-Cyclone commented on src/core/blockchain/web3-pure/constants/empty-address.ts
> +export const EMPTY_ADDRESS = '0x0000000000000000000000000000000000000000';
Done.

2023-02-21 09:10 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/changenow-provider/changenow-cross-chain-provider.ts
> +    readonly type = CROSS_CHAIN_TRADE_TYPE.CHANGENOW;
Done.

2023-02-21 09:10 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/changenow-provider/changenow-cross-chain-provider.ts
> +            {
Done.

2023-02-21 09:11 UTC, Doctor-Cyclone commented on src/features/cross-chain/status-manager/cross-chain-status-manager.ts
> +                    params: {
Done.

2023-02-21 09:15 UTC, axtezy approved these changes

2023-02-21 09:46 UTC, merged