fix price impact
Cryptorubic/rubic-sdk pull request #368
Opened 2023-04-27 15:55 UTC by Doctor-Cyclone

2023-04-28 09:11 UTC, axtezy approved these changes

2023-05-10 07:37 UTC, axtezy requested changes

2023-05-10 07:37 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/lifi-provider/lifi-cross-chain-trade.ts
> +            priceImpact: number | null;
В аппе как null обрабатывается?

2023-05-10 07:37 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/multichain-provider/multichain-cross-chain-provider.ts
> +                    priceImpact: onChainTrade?.from ? from.calculatePriceImpactPercent(to) || 0 : 0,
можно упростить

2023-05-10 09:26 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/multichain-provider/multichain-cross-chain-provider.ts
> +                    priceImpact: onChainTrade?.from ? from.calculatePriceImpactPercent(to) || 0 : 0,
Done.

2023-05-10 09:26 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/lifi-provider/lifi-cross-chain-trade.ts
> +            priceImpact: number | null;
Done.

2023-05-10 09:28 UTC, axtezy approved these changes

2023-05-10 09:29 UTC, merged