add prependedOperatingExpenseCost for DLN
Cryptorubic/rubic-sdk pull request #373
Opened 2023-05-11 06:43 UTC by Doctor-Cyclone

2023-05-11 07:24 UTC, axtezy requested changes
Нужно убедиться что amount нужны подставляется, потому что есть amount, есть recommendedAmount в ответе на получение рейтов. Они не отличались раньше, но с учетом включения prependOperatingExpenses, там должны разные суммы приходить, и брать надо ту что меньше

2023-05-11 07:24 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/models/transaction-response.ts
> +    prependedOperatingExpenseCost: 'string';
точно такой тип?)

2023-05-11 15:08 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/models/transaction-response.ts
> +    prependedOperatingExpenseCost: 'string';
Done.

2023-05-15 13:39 UTC, axtezy requested changes

2023-05-15 13:39 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/constants/gate-contract-abi.ts
> +export const DE_BRIDGE_GATE_CONTRACT_ABI = [
: AbiItem[] и не as

2023-05-15 13:39 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/debridge-cross-chain-provider.ts
> +            // const cryptoFeeAmount = new BigNumber(tx.value).minus(
комменты убрать

2023-05-15 13:39 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/debridge-cross-chain-provider.ts
> +            const deBridgeGateAddress = await web3Public.callContractMethod(
запросы в блокчейн в отдельные методы

2023-05-15 14:08 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/debridge-cross-chain-provider.ts
> +            // const cryptoFeeAmount = new BigNumber(tx.value).minus(
Done.

2023-05-15 14:08 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/debridge-cross-chain-provider.ts
> +            const deBridgeGateAddress = await web3Public.callContractMethod(
Done.

2023-05-16 10:43 UTC, axtezy approved these changes

2023-05-16 10:43 UTC, merged