Add aerodrome dex for base chain
Cryptorubic/rubic-sdk pull request #451
Opened 2023-09-06 11:48 UTC by Doctor-Cyclone

2023-09-12 11:19 UTC, axtezy requested changes

2023-09-12 12:38 UTC, Doctor-Cyclone commented on src/features/on-chain/calculation-manager/providers/dexes/base/aerodrome/aerodrome-abi.ts
> +    {
Done.

2023-09-12 12:38 UTC, Doctor-Cyclone commented on src/features/on-chain/calculation-manager/providers/dexes/base/aerodrome/aerodrome-path-factory.ts
> +                if (tokens.length > 3) {
Done.

2023-09-12 12:40 UTC, axtezy approved these changes

2023-09-15 07:11 UTC, axtezy approved these changes

2023-09-15 07:12 UTC, merged