add dln provider
Cryptorubic/rubic-sdk pull request #488
Opened 2023-11-01 14:29 UTC by PseudoElement

2023-11-02 11:00 UTC, axtezy requested changes

2023-11-02 11:00 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/constants/portal-address.ts
> +    [BLOCKCHAIN_NAME.OPTIMISM]: ''
Нашел адрес, но он все равно не используется по идее, но на всякий лучше вписать
0x292fC50e4eB66C3f6514b9E402dBc25961824D62

2023-11-02 15:54 UTC, PseudoElement commented on src/features/cross-chain/calculation-manager/providers/debridge-provider/constants/portal-address.ts
> +    [BLOCKCHAIN_NAME.OPTIMISM]: ''
добавил аддрес

2023-11-03 08:06 UTC, axtezy approved these changes
Апрувнул, но пока QA не скажет - не мержем

2023-11-03 11:04 UTC, axtezy approved these changes

2023-12-13 07:25 UTC, closed without merging