Rubic 1800
Cryptorubic/rubic-sdk pull request #500
Opened 2023-11-10 14:01 UTC by PseudoElement

2023-11-10 14:09 UTC, axtezy requested changes

2023-11-10 14:09 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/lifi/constants/lifi-providers.ts
> +export const LIFI_AGGREGATOR = 'LIFI';
Не нужно

2023-11-10 14:09 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/lifi/lifi-provider.ts
> +                    const type = LIFI_AGGREGATOR;
`const type = ON_CHAIN_TRADE_TYPE.LIFI`

2023-11-13 07:54 UTC, axtezy requested changes

2023-11-13 07:54 UTC, axtezy commented on src/features/on-chain/calculation-manager/on-chain-manager.ts
> +    private filterTradesWithBestLifiTrade(
Лучше чтобы на уровне провайдера Lifi возвращал только 1 трейд

2023-11-13 09:38 UTC, axtezy requested changes

2023-11-13 09:38 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/lifi/lifi-provider.ts
> +        const bestLifiTrade = trades.reduce((bestTrade, trade) => {
Вместо reduce - sort

2023-11-13 09:38 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/lifi/lifi-provider.ts
> +    private filterTradesWithBestLifiTrade(trades: LifiTrade[]): LifiTrade {
Вместо filterTradesWithBestLifiTrade - findBestTrade/pickBestTrade

2023-11-13 09:38 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/lifi/lifi-provider.ts
> +                        withDeflation: fullOptions.withDeflation!
Зачем добавлять? в Full Options и так он не опциональный и всегда будет
Аналогично и useProxy

2023-11-13 09:39 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/lifi/lifi-provider.ts
> +                        withDeflation: fullOptions.withDeflation!
забыл убрать, изначально хотел вынести в отдельный метод, там были проблемы с типами

2023-11-14 08:51 UTC, axtezy requested changes
Ок, ставь прод версию

2023-11-14 10:42 UTC, PseudoElement commented
Поставил

2023-11-23 14:19 UTC, axtezy requested changes

2023-11-23 14:19 UTC, axtezy commented on package.json
> +    "version": "4.39.1",
4.39.2, 1 уже есть

2023-11-23 20:01 UTC, axtezy approved these changes

2023-11-23 20:54 UTC, merged