Feature/updated ccr
Cryptorubic/rubic-sdk pull request #51
Opened 2022-02-21 10:54 UTC by ottebrut

2022-02-21 15:22 UTC, siandreev requested changes

2022-02-21 15:22 UTC, siandreev commented on src/features/cross-chain/cross-chain-manager.ts
> +        const promises: Promise<InstantTradeCalculatedTrade>[] = contract.providersData.map(
Все что ниже я бы вынес в отдельный метод. А то в этом методе логика такая:

если ...
то создать прямой трейд
иначе 
сделать кучу всего, чтобы создать не прямой трейд

Имхо будет лучше так:

если ...
то создать прямой трейд
иначе 
создать не прямой трейд

2022-02-21 15:22 UTC, siandreev commented on src/features/cross-chain/models/cross-chain-supported-instant-trade.ts
> +export type CrossChainSupportedInstantTrade =
Нельзя вытащить из юниона сверху?

2022-02-21 15:22 UTC, siandreev commented on src/features/swap/dexes/common/oneinch-common/oneinch-abstract-provider.ts
> +                throw new Error('Address is not set');
RubicSdkError

2022-02-21 15:32 UTC, ottebrut commented on src/features/cross-chain/contract-trade/instant-trade-contract-trade.ts
> +            });
Нет, тут кодируется именно для нашего контракта кросс чейна

2022-02-21 15:34 UTC, ottebrut commented on src/features/cross-chain/contract-trade/instant-trade-contract-trade.ts
> +
В случае аглебры: firstPath надо кодировать, secondPath не нужно

2022-02-21 15:38 UTC, ottebrut commented on src/features/cross-chain/cross-chain-manager.ts
> +interface InstantTradeCalculatedTrade {
Это локальный интерфейс в кросс чейн менеджере, не вижу смысла добавлять кроссчейн в название. Переименовал в `ItCalculatedTrade`

2022-02-21 15:41 UTC, ottebrut commented on src/features/cross-chain/models/cross-chain-supported-instant-trade.ts
> +export type CrossChainSupportedInstantTrade =
Не представляю как

2022-02-21 15:42 UTC, ottebrut commented on src/features/swap/dexes/common/oneinch-common/oneinch-abstract-provider.ts
> +                throw new Error('Address is not set');
Не нужно. Эта строчка обернута в try catch, ошибка сразу поймается и никуда не передастся, просто вызовется другой метод апи.

2022-02-21 16:10 UTC, ottebrut commented on src/features/cross-chain/contract-trade/contract-trade.ts
> +
поправил

2022-02-21 16:10 UTC, ottebrut commented on src/features/cross-chain/constants/cross-chain-contracts.ts
> +        address: '0xe6625BBE80710C7Bb473721EdAC24Ce326940a6f',
забыл вернуть, поправил

2022-02-21 16:10 UTC, ottebrut commented on src/features/cross-chain/contract-trade/instant-trade-contract-trade.ts
> +        if (this.instantTrade instanceof OneinchTrade) {
добавил новые классы для провайдеров

2022-02-22 12:22 UTC, siandreev commented on src/features/cross-chain/contract-trade/it-contract-trade/it-cross-chain-contract-trade.ts
> +    }
свич кейс

2022-02-22 12:28 UTC, siandreev approved these changes

2022-02-22 12:29 UTC, merged