Add Bitcoin in Symbiosis
Cryptorubic/rubic-sdk pull request #544
Opened 2024-01-24 08:29 UTC by Doctor-Cyclone

2024-01-24 08:57 UTC, axtezy approved these changes

2024-01-25 14:37 UTC, axtezy requested changes

2024-01-25 14:37 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/common/proxy-cross-chain-evm-facade/proxy-cross-chain-evm-trade.ts
> +        if (toChainId === blockchainId[BLOCKCHAIN_NAME.BITCOIN]) {
В функцию гет ресивер

2024-01-25 14:39 UTC, axtezy requested changes

2024-01-25 14:39 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/symbiosis-provider/symbiosis-cross-chain-provider.ts
> +            if (toBlockchain === BLOCKCHAIN_NAME.BITCOIN && !options.receiverAddress) {
Вынести в функцию гет ресивер

2024-01-25 14:39 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/symbiosis-provider/symbiosis-cross-chain-trade.ts
> +        if (this.to.blockchain === BLOCKCHAIN_NAME.BITCOIN) {
Вынести в функцию гет реверт адрес

2024-01-25 15:01 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/common/proxy-cross-chain-evm-facade/proxy-cross-chain-evm-trade.ts
> +        if (toChainId === blockchainId[BLOCKCHAIN_NAME.BITCOIN]) {
Done.

2024-01-25 15:01 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/symbiosis-provider/symbiosis-cross-chain-trade.ts
> +        if (this.to.blockchain === BLOCKCHAIN_NAME.BITCOIN) {
Done.

2024-01-25 15:03 UTC, axtezy approved these changes

2024-01-25 15:04 UTC, merged