Rubic 2132
Cryptorubic/rubic-sdk pull request #555
Opened 2024-02-02 12:29 UTC by axtezy

2024-02-02 14:33 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/dln/chains/dln-solana-on-chain-trade.ts
> +        // const fromBlockchain = tradeStruct.from.blockchain;
todo

2024-02-02 14:33 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/dln/dln-on-chain-provider.ts
> +        return null;
todo

2024-02-02 16:57 UTC, PseudoElement commented on src/core/blockchain/web3-public-service/web3-public/evm-web3-public/evm-web3-public.ts
> +        const indexOfNativeCoin = tokensAddresses.findIndex(EvmWeb3Pure.isNativeAddress);
findIndex callback принимает, ты наверное перепутал с indexOf

2024-02-08 16:46 UTC, PseudoElement requested changes

2024-02-08 16:46 UTC, PseudoElement commented on src/features/cross-chain/calculation-manager/providers/common/solana-cross-chain-trade/solana-cross-chain-trade.ts
> +    public getUsdPrice(providerFeeToken?: BigNumber): BigNumber {
можно из евм/соляны/трона вынести в crosschain-trade

2024-02-12 15:22 UTC, axtezy commented on src/core/blockchain/web3-public-service/web3-public/solana-web3-public/solana-web3-public.ts
> +                _rpcRequest: (owner: string, data: unknown[]) => ReturnValue;
Connection не наш интерфейс а из либы, но она не поддерживает прямой вызов методов (хотя на самом деле умеет). Можно было бы вынести в отдельный интерфейс, но _rpcRequest используется только здесь

2024-02-12 15:24 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/common/solana-cross-chain-trade/solana-cross-chain-trade.ts
> +        return this.swapWithParams(options);
В целом необязательно тк proxy всегда будет false, но сделал более явно

2024-02-12 15:28 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/common/solana-cross-chain-trade/solana-cross-chain-trade.ts
> +    public getUsdPrice(providerFeeToken?: BigNumber): BigNumber {
Не нужно. Evm и Solana сейчас имеет одинаковый код, но трон отличается, потенциально новые типы сетей тоже могут другую логику иметь

2024-02-12 15:40 UTC, axtezy commented on src/core/blockchain/web3-public-service/web3-public/tron-web3-public/tron-web3-public.ts
> +        );
Аналогичный код для евм используется, пока не готовы с ним расстаться, но нужно будет придумать как лучше сделать, чтобы часть еще в общийй абстрактный класс вынести. Оставил туду

2024-02-13 13:00 UTC, PseudoElement approved these changes

2024-02-13 13:03 UTC, merged