Fix bugs pack
Cryptorubic/rubic-sdk pull request #563
Opened 2024-02-08 18:35 UTC by Doctor-Cyclone

2024-02-09 10:09 UTC, axtezy requested changes

2024-02-09 10:09 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/bridgers-provider/utils/get-method-arguments-and-transaction-data.ts
> +                'value' in transactionData ? transactionData : { data: '', to: '', value: '' },
Что за конструкция?

2024-02-09 10:41 UTC, Doctor-Cyclone commented on src/features/cross-chain/calculation-manager/providers/bridgers-provider/utils/get-method-arguments-and-transaction-data.ts
> +                'value' in transactionData ? transactionData : { data: '', to: '', value: '' },
Есть в **transactionData** есть поле **value**, значит это **EVM data** и можно её прокинуть в аргументы, если нет, то это **TRON data**, но у неё нет нужных полей и я прокидываю как в CN просто объект

2024-02-09 11:34 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/bridgers-provider/utils/get-method-arguments-and-transaction-data.ts
> +                'value' in transactionData ? transactionData : { data: '', to: '', value: '' },
так в троне те же самые поля

2024-02-12 07:49 UTC, axtezy approved these changes

2024-02-12 07:51 UTC, merged