Update CoinGecko api service
Cryptorubic/rubic-sdk pull request #606
Opened 2024-04-05 12:49 UTC by Doctor-Cyclone

2024-04-05 12:56 UTC, axtezy requested changes

2024-04-05 12:56 UTC, axtezy commented on src/core/coingecko-api/coingecko-api.ts
> +    private async getTokenPriceFromBackend(
Это должен быть публичный метод. Его теперь использовать будут новые интеграторы и мы с аппа

2024-04-05 12:56 UTC, axtezy commented on src/core/coingecko-api/coingecko-api.ts
> +        if (!CoingeckoApi.isSupportedBlockchain(token.blockchain)) {
Тут и в других методах должен только вызываться новый метод + формироваться данные для его вызова, без обработки разных ошибок

2024-04-05 13:13 UTC, Doctor-Cyclone commented on src/core/coingecko-api/coingecko-api.ts
> +    private async getTokenPriceFromBackend(
Done.

2024-04-05 13:31 UTC, axtezy requested changes

2024-04-05 13:31 UTC, axtezy commented on src/core/coingecko-api/coingecko-api.ts
> +    public async getTokenPriceFromBackend(
Просто getTokenPrice

2024-04-05 14:09 UTC, Doctor-Cyclone commented on src/core/coingecko-api/coingecko-api.ts
> +    public async getTokenPriceFromBackend(
Done.

2024-04-09 13:17 UTC, axtezy requested changes

2024-04-09 13:17 UTC, axtezy commented on src/core/coingecko-api/coingecko-api.ts
> +                `https://dev-tokens.rubic.exchange/api/v1/tokens/price/${network
Мы всегда с дева будем брать цены?

2024-04-09 13:23 UTC, Doctor-Cyclone commented on src/core/coingecko-api/coingecko-api.ts
> +                `https://dev-tokens.rubic.exchange/api/v1/tokens/price/${network
Done.

2024-04-09 13:34 UTC, merged