Add EddyFinance dex
Cryptorubic/rubic-sdk pull request #638
Opened 2024-05-17 09:48 UTC by Doctor-Cyclone

2024-05-21 13:53 UTC, axtezy requested changes

2024-05-21 13:53 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +        if (
переопределить в дочеренем классе

2024-06-11 10:55 UTC, Doctor-Cyclone commented on src/features/on-chain/calculation-manager/providers/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +        if (
Done.

2024-06-11 10:57 UTC, axtezy approved these changes

2024-06-11 11:01 UTC, merged