add ZetaSwap & NativeRouter providers
Cryptorubic/rubic-sdk pull request #651
Opened 2024-06-07 06:53 UTC by IDIDOS

2024-06-07 07:48 UTC, axtezy requested changes

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/native-router/native-router-trade.ts
> +    constructor(
Можно тоже без конструктора

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +    constructor(tradeType: OnChainTradeType) {
Можно не добавлять конструктор

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +    public readonly tradeType: OnChainTradeType;
Можно не обозначать поле, оно уже от AggregatorOnChainProvider наследуется, просто в экземпляре указать

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +        return nativeRouterAbstractSupportedBlockchains.filter(
Вместо filter(...)[0] лучше просто find(...) использовать

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/services/native-router-api-service.ts
> +    // public static async getIndicativeQuote(request: NativeRouterQuoteRequestParams): Promise<NativeRouterQuoteResponse> {
Удаляем

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/services/native-router-api-service.ts
> +    public static async getChains(): Promise<NativeRouterChain[]> {
Не вижу использований

2024-06-07 07:48 UTC, axtezy commented on src/index.ts
> +// created from 'create-ts-index'
Этот файл не должен в гит заливаться, он только для сборки, странно, что не удалился

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +            const chain = (await this.getBlockchainById(fromChainId)) as string;
Без await

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +    private readonly defaultOptions: RequiredOnChainCalculationOptions = {
Дефолтные опции полностью равны evmProviderDefaultOptions, можно не использовать тогда

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +                useProxy: this.defaultOptions.useProxy,
Из дефолтных опций ничего не берем, только из передаваемых options
Если нам нужно соединить передаваемые options и default, используем такую конструкцию
```
const fullOptions = combineOptions(options, this.defaultOptions);
```

2024-06-07 07:48 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/constants/native-router-abstract-supported-blockchains.ts
> +        chainId: 56,
нам label, isMainnet, token не сильно интересуют, можем сделать просто такой маппинг

```
type AllSupportedNetworks = ZetaswapOnChainSupportedBlockchains | NativeRouterSupportedBlockchains;
```
И объект
```
const blockchainNameMapping: Record<AllSupportedNetworks, string> = {
  [BLOCKCHAIN_NAME.ETHEREUM]: 'ethereum',
  ...
} 
```
Потом, где надо, обращаться просто `blockchainNameMapping[fromToken.blockchain]`

2024-06-07 09:16 UTC, PseudoElement requested changes

2024-06-07 09:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/native-router/native-router-trade.ts
> +export class NativeRouterTrade extends NativeRouterAbstractTrade {
у тебя NativeRouterTrade и ZetaSwapTrade должны использоваться в калькуляции вместо NativeRouterAbstractTrade - соотвественно есть две опции:
1 - имплементировать метод calculate отдельно в ZetaswapProvider и NativeRouterProvider
2 - сделать NativeRouterAbstractTrade абстрактным, чтобы возвращались экземпляры классов ZetaSwapTrade и NativeRouterTrade.

2024-06-07 09:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-trade.ts
> +    public readonly type = ON_CHAIN_TRADE_TYPE.NATIVE_ROUTER;
Это поле должно быть абстрактным, которое определяетс я в наследниках(ZetaSwap, NativeRouterTrade) - в текущей итерации у тебя всегд будет возвращаться ON_CHAIN_TRADE_TYPE.NATIVE_ROUTER для всех наследников и такой сущности как ZetaSwapTrade не существует как явления.

2024-06-07 09:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/native-router-abstract-provider.ts
> +    protected isSupportedBlockchain(blockchain: BlockchainName): boolean {
бесполезный метод в этой абстракции, удали отсюда, он у тебя реализован в инстэнсах

2024-06-07 09:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/common/native-router-abstract/constants/native-router-abstract-supported-blockchains.ts
> +        chainId: 56,
Поддерживаю, используется по факту только chain поле

2024-06-07 09:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/zetaswap/zetaswap-provider.ts
> +export class ZetaswapProvider extends NativeRouterAbstractProvider {
лучше назвать ZetaSwap трейд и провайдер

2024-06-07 13:15 UTC, PseudoElement requested changes

2024-06-07 13:16 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/aggregators/zetaswap/constants/zetaswap-supported-blockchains.ts
> +export const zetaswapOnChainSupportedBlockchains = [BLOCKCHAIN_NAME.ZETACHAIN] as const;
что дон?

2024-06-17 18:38 UTC, axtezy approved these changes

2024-06-17 18:44 UTC, PseudoElement approved these changes

2024-06-17 18:48 UTC, merged