2456, init eddy-bridge
Cryptorubic/rubic-sdk pull request #660
Opened 2024-06-20 15:39 UTC by PseudoElement

2024-06-26 13:43 UTC, axtezy requested changes

2024-06-26 13:43 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/constants/edyy-bridge-abi.ts
> +        inputs: [],
почисить неиспользуемые функици аби

2024-06-26 13:43 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +                this.getToTokenAmount(from, toToken, options),
в getToTokenAmount должен идти fromWithoutFee

2024-06-26 13:43 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +        const supportedTokens = ['eth', 'bnb', 'zeta'];
А свап в btc.btc в зетачейне?

2024-06-26 13:43 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-trade.ts
> +            slippage: 0,
слиппейдж будет равен слиппейджу который мы в он-чейн трейд закладываем

2024-06-26 13:43 UTC, axtezy commented on src/features/on-chain/calculation-manager/providers/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +        if (
Это функция специально protected помечена, если нужно переделать, переопределяй метод в инстансе класса определенного (eddy-finance-dex)

2024-06-26 13:45 UTC, PseudoElement commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +        const supportedTokens = ['eth', 'bnb', 'zeta'];
Женя сказал без биткоина интегрируем

2024-06-26 13:47 UTC, PseudoElement commented on src/features/on-chain/calculation-manager/providers/dexes/common/uniswap-v2-abstract/uniswap-v2-abstract-trade.ts
> +        if (
так зачем ее копипастить в наследнике? Она и там и тут будет протектед, просто код общий оставить

2024-07-09 07:30 UTC, axtezy requested changes

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +        const supportedTokens = ['eth', 'bnb', 'zeta'];
Если есть возможность, лучше адреса всегда использовать

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/utils/eddy-bridge-routing-directions.ts
> +    if (
```
if (
  from.blockchain === BLOCKCHAIN_NAME.ZETACHAIN &&
  from.symbol.toLowerCase() === to.symbol.toLowerCase() &&
  !from.isNative
) {
  return ERD.ZETA_TOKEN_TO_ANY_CHAIN_NATIVE;
}
if (from.blockchain === BLOCKCHAIN_NAME.ZETACHAIN && from.isNative) {
  return ERD.ZETA_NATIVE_TO_ANY_CHAIN_NATIVE;
}
if (from.blockchain !== BLOCKCHAIN_NAME.ZETACHAIN && from.isNative && to.isNative) {
  return ERD.ANY_CHAIN_NATIVE_TO_ZETA_NATIVE;
}
throw new NotSupportedTokensError();
```

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +    private routingDirection!: EddyRoutingDirection;
Зачем хранить? Передавай время калькуляции в метод

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +            const gasInTargetChainNonWei = await EddyBridgeContractService.getGasInTargetChain(
Лучше в калькуляции посчитать, потом в этот метод передавать

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +        } else if (this.routingDirection === ERD.ZETA_NATIVE_TO_ANY_CHAIN_NATIVE) {
если return стейтмент есть ранее, else не ставим

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-provider.ts
> +                decimals: 18,
У всех токенов 18 децималс? Лучше через createToken создавать
Аналогично ниже

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/eddy-bridge-trade.ts
> +                const prevAmountPlusOnePercent =
Что за махинации? Совершенно не прозрачно, лучше рекалькуляцию to с учетом нового newGasAmount делать, и передавать сразу новый to

2024-07-09 07:30 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/utils/get-eddy-bridge-dst-status.ts
> +        const cctxRes = await Injector.httpClient.get<CctxHashResponse>(`
Ошибок кросс-чейна у них не предусмотрено? Всегда либо pending либо success?

2024-07-09 08:22 UTC, PseudoElement commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/utils/get-eddy-bridge-dst-status.ts
> +        const cctxRes = await Injector.httpClient.get<CctxHashResponse>(`
они про ошибки не упомянули

2024-07-09 09:27 UTC, axtezy commented on src/features/cross-chain/calculation-manager/providers/eddy-bridge/utils/get-eddy-bridge-dst-status.ts
> +        const cctxRes = await Injector.httpClient.get<CctxHashResponse>(`
Добавь туду, 100% есть случаи, когда транза фейлится и они в апи это показывают

2024-07-09 09:32 UTC, merged